# Generated by Django 2.0.3 on 2018-03-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomde do Evento', models.CharField(max_length=40)),
                ('Descrição', models.TextField(max_length=70)),
                ('Data do evento', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('Hora', models.TimeField()),
            ],
        ),
    ]
