# Generated by Django 2.0.2 on 2018-02-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=25)),
                ('porte', models.CharField(choices=[('pp', 'Muito pequeno'), ('p', 'Pequeno'), ('m', 'Medio'), ('g', 'Grande'), ('gg', 'Muito grande')], max_length=10)),
                ('genero', models.CharField(choices=[('masc', 'Masculino'), ('fem', 'Feminino')], max_length=5)),
                ('ra', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10, null=True)),
                ('img', models.CharField(max_length=10000, null=True)),
                ('restricao_doacao', models.BooleanField(default=False)),
                ('saude', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('castracao', models.BooleanField(default=False)),
                ('coleira', models.CharField(max_length=15)),
                ('endereco', models.CharField(default='Esse dado virá de outro app --provavel--', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_especie', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Categoria'),
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Especie'),
        ),
    ]
