# Generated by Django 2.0.3 on 2018-03-23 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data da adoção', models.DateField()),
                ('Hora da doação', models.TimeField()),
                ('Contrato de adoção', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ra', models.IntegerField()),
                ('raca', models.CharField(max_length=25)),
                ('idade', models.IntegerField()),
                ('porte', models.CharField(choices=[('pp', 'Muito pequeno'), ('p', 'Pequeno'), ('m', 'Medio'), ('g', 'Grande'), ('gg', 'Muito grande')], max_length=10)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Indefinido', 'Indefinido')], max_length=10)),
                ('castrado', models.BooleanField(default=False)),
                ('origem', models.CharField(max_length=30)),
                ('Comportamento', models.CharField(max_length=30)),
                ('Descrição da saúde do animal', models.TextField(max_length=600)),
            ],
        ),
        migrations.AddField(
            model_name='adocao',
            name='Animal a ser adotado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='Nome do usuário',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
    ]
